name: Release

on:
  # Run the workflow each time new commits are pushed to the candidate branch. 
  push:
    branches: [ "candidate" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  build:
    name: 🧪 Build new release on arm64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - arm64
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v1
    - uses: diddlesnaps/snapcraft-multiarch-action@v1
      with:
        architecture: ${{ matrix.platform }}
        - uses: actions/upload-artifact@v2
    - uses: actions/upload-artifact@v2
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}